- id: hiera_override
  type: puppet
  groups: [primary-controller, controller, compute, ironic-compute, compute-vmware, cinder, cinder-vmware, primary-mongo, mongo, ceph-osd, virt]
  required_for: [globals, deploy_end]
  requires: [hiera]
  parameters:
    puppet_manifest: "puppet/manifests/hiera_override.pp"
    puppet_modules: "puppet/modules:/etc/puppet/modules"
    timeout: 3600

- id: fuel-ssl-keys-saving
  type: puppet
  groups: [primary-controller, controller, compute, compute-vmware, cinder, cinder-vmware, primary-mongo, mongo, ceph-osd, virt]
  requires: [firewall]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/ssl/ssl_keys_saving.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: fuel-ssl-add-trust-chain
  type: puppet
  groups: [primary-controller, controller, compute, compute-vmware, cinder, cinder-vmware, primary-mongo, mongo, ceph-osd, virt]
  requires: [firewall, ssl-keys-saving]
  required_for: [hosts]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/ssl/ssl_add_trust_chain.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: fuel-ssl-dns-setup
  type: puppet
  groups: [primary-controller, controller]
  requires: [firewall, ssl-add-trust-chain, hosts]
  required_for: [cluster]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/ssl/ssl_dns_setup.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
